import 'package:flutter/foundation.dart';
import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/turf_pitch_model.dart';
import '../repositories/turf_pitch_repository.dart';

class TurfProvider extends ChangeNotifier {
  final TurfPitchRepository _pitchRepository = TurfPitchRepository();
  
  List<TurfPitchModel> _pitches = [];
  bool _isLoading = false;
  String? _errorMessage;
  StreamSubscription<List<TurfPitchModel>>? _pitchesSubscription;
  String? _currentOwnerId;

  // Getters
  List<TurfPitchModel> get pitches => _pitches;
  int get pitchCount => _pitches.length;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  // Load all pitches
  Future<void> loadAllPitches() async {
    try {
      _setLoading(true);
      _clearError();

      _pitches = await _pitchRepository.getAllPitches();

    } catch (e) {
      _setError('Failed to load pitches: $e');
    } finally {
      _setLoading(false);
    }
  }

  // Load pitches by owner
  Future<void> loadPitchesByOwner(String ownerId) async {
    try {
      _setLoading(true);
      _clearError();
      _currentOwnerId = ownerId;

      _pitches = await _pitchRepository.getPitchesByManager(ownerId);

    } catch (e) {
      _setError('Failed to load pitches: $e');
    } finally {
      _setLoading(false);
    }
  }

  // Listen to pitches by owner (real-time)
  void listenToPitchesByOwner(String ownerId) {
    _currentOwnerId = ownerId;
    _pitchesSubscription?.cancel();
    _pitchesSubscription = _pitchRepository
        .listenToPitchesByManager(ownerId)
        .listen(
      (pitches) {
        _pitches = pitches;
        notifyListeners();
      },
      onError: (error) {
        _setError('Failed to listen to pitches: $error');
      },
    );
  }

  // Listen to all active pitches (real-time)
  void listenToActivePitches() {
    _pitchesSubscription?.cancel();
    _pitchesSubscription = _pitchRepository
        .listenToActivePitches()
        .listen(
      (pitches) {
        _pitches = pitches;
        notifyListeners();
      },
      onError: (error) {
        _setError('Failed to listen to pitches: $error');
      },
    );
  }

  // Add a new pitch
  Future<TurfPitchModel?> addPitch({
    required String name,
    required String type,
    required String ownerId,
    required double pricePerHour,
    String? description,
    List<String>? amenities,
  }) async {
    try {
      _setLoading(true);
      _clearError();

      final now = DateTime.now();
      final newPitch = TurfPitchModel(
        id: '', // Will be generated by repository
        name: name,
        type: type,
        managerId: ownerId,
        pricePerHour: pricePerHour,
        description: description,
        amenities: amenities,
        createdAt: now,
        updatedAt: now,
      );

      final createdPitch = await _pitchRepository.createPitch(newPitch);

      // Add to local list if not using real-time listener
      if (_pitchesSubscription == null) {
        _pitches.add(createdPitch);
        notifyListeners();
      }

      return createdPitch;
    } catch (e) {
      _setError('Failed to add pitch: $e');
      return null;
    } finally {
      _setLoading(false);
    }
  }

  // Update pitch
  Future<bool> updatePitch(String id, Map<String, dynamic> data) async {
    try {
      _setLoading(true);
      _clearError();

      await _pitchRepository.updatePitch(id, data);

      // Update local list if not using real-time listener
      if (_pitchesSubscription == null) {
        final index = _pitches.indexWhere((p) => p.id == id);
        if (index != -1) {
          // Reload the pitch
          final updatedPitch = await _pitchRepository.getPitchById(id);
          if (updatedPitch != null) {
            _pitches[index] = updatedPitch;
            notifyListeners();
          }
        }
      }

      return true;
    } catch (e) {
      _setError('Failed to update pitch: $e');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Delete pitch
  Future<bool> deletePitch(String id) async {
    try {
      _setLoading(true);
      _clearError();

      await _pitchRepository.deletePitch(id);

      // Remove from local list if not using real-time listener
      if (_pitchesSubscription == null) {
        _pitches.removeWhere((p) => p.id == id);
        notifyListeners();
      }

      return true;
    } catch (e) {
      _setError('Failed to delete pitch: $e');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Toggle pitch active status
  Future<bool> togglePitchStatus(String id, bool isActive) async {
    return await updatePitch(id, {'isActive': isActive});
  }

  // Get pitch by ID
  TurfPitchModel? getPitchById(String id) {
    try {
      return _pitches.firstWhere((pitch) => pitch.id == id);
    } catch (e) {
      return null;
    }
  }

  // Get active pitches
  List<TurfPitchModel> getActivePitches() {
    return _pitches.where((pitch) => pitch.isActive).toList();
  }

  // Get inactive pitches
  List<TurfPitchModel> getInactivePitches() {
    return _pitches.where((pitch) => !pitch.isActive).toList();
  }

  // Helper methods
  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }

  void _setError(String error) {
    _errorMessage = error;
    notifyListeners();
  }

  void _clearError() {
    _errorMessage = null;
  }

  @override
  void dispose() {
    _pitchesSubscription?.cancel();
    super.dispose();
  }
}
